# Generated by Django 4.2.21 on 2025-05-24 16:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(max_length=400, verbose_name='نام کالا به فارسی')),
                ('en_title', models.CharField(max_length=400, verbose_name='نام کالا به انگلیسی')),
                ('short_title', models.CharField(max_length=100, verbose_name='عنوان کوتاه')),
                ('url_title', models.SlugField(allow_unicode=True, blank=True, default='', max_length=300, null=True, unique=True, verbose_name='عنوان در url')),
                ('inventory', models.PositiveIntegerField(default=1, verbose_name='موجودی کالا')),
                ('price', models.IntegerField(help_text='قیمت پیش از تخفیف مد نظر است.', verbose_name='قیمت به ریال')),
                ('off', models.IntegerField(default=0, help_text='مقدار عددی وارد شود', verbose_name='درصد تخفیف')),
                ('new_price', models.IntegerField(blank=True, help_text='این فیلد به صورت خودکار جنریت میشود.', null=True, verbose_name='قیمت با تخفیف')),
                ('identify', models.CharField(help_text='این فیلد به صورت خودکار جنریت میشود.', max_length=12, verbose_name='شناسه کالا')),
                ('description', models.TextField(verbose_name='توضیحات کالا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_brand', models.CharField(max_length=50, verbose_name='نام برند به فارسی')),
                ('en_brand', models.CharField(max_length=50, verbose_name='نام برند به انگلیسی')),
                ('url_title', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['en_brand'],
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.CharField(choices=[('DF', 'Pending - (در دست بررسی)'), ('PB', 'Published - (منتشر شده)'), ('RJ', 'Rejected - (رد شده)')], default='DF', max_length=2, verbose_name='وضعیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productcomment', verbose_name='پاسخ نظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'نظر یا کامنت',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='فروشنده')),
                ('location', models.CharField(max_length=60, verbose_name='شهر')),
                ('card', models.IntegerField(verbose_name='شماره کارت فروشنده')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشنده ها',
            },
        ),
        migrations.CreateModel(
            name='Weak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='نقطه ضعف کالا')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaks', to='product_module.productcomment', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'نقطه ضعف کالا',
                'verbose_name_plural': 'نقاط ضعف کالا ها',
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='نقطه قوت کالا')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='product_module.productcomment', verbose_name='نظر')),
            ],
            options={
                'verbose_name': 'نقطه قوت کالا',
                'verbose_name_plural': 'نقاط قوت کالا ها',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/products/product_images/%Y/%m/%d', verbose_name='تصویر محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='product_module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='shop/products/product_specification_detail_images/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdc_spc_details', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'توضیحات بیشتر مشخصه کالا',
                'verbose_name_plural': 'توضیحات بیشتر مشخصات کالا ها',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='عنوان مشخصه')),
                ('value', models.CharField(max_length=75, verbose_name='مقدار مشخصه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'ویژگی کالا',
                'verbose_name_plural': 'ویژگی های کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: sm, md, lg, xl', max_length=4, verbose_name='سایز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سایز محصول',
                'verbose_name_plural': 'سایزهای محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='معرفی محصول', max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='معرفی و توضیحات محصول')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_desc', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'توضیحات کالا',
                'verbose_name_plural': 'توضیحات کالا',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='نام رنگ')),
                ('color_hex', models.CharField(max_length=14, verbose_name='کد رنگ (hex)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color', to='product_module.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'رنگ محصول',
                'verbose_name_plural': 'رنگ های محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی به فارسی')),
                ('en_title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی به انگلیسی')),
                ('url_title', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(db_index=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(db_index=True, verbose_name='حذف شده / نشده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.productcategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['en_title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.productbrand', verbose_name='برند کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='product_module.productcategory', verbose_name='دسته بندی کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_module.seller', verbose_name='فروشنده کالا'),
        ),
        migrations.AddIndex(
            model_name='productcomment',
            index=models.Index(fields=['status'], name='product_mod_status_a6b3be_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active', 'is_delete'], name='product_mod_is_acti_e4e5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_delete', 'new_price', 'created_at', 'updated_at'], name='product_mod_is_acti_b20fbe_idx'),
        ),
    ]
