# Generated by Django 4.2.9 on 2025-05-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_title',
            new_name='slug',
        ),
    ]
