# Generated by Django 4.2.9 on 2025-05-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_rename_url_title_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weak',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weak', to='product_module.productcomment', verbose_name='نظر'),
        ),
    ]
