# Generated by Django 4.2.9 on 2025-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_alter_weak_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identify',
            field=models.CharField(default='', help_text='این فیلد به صورت خودکار جنریت میشود.', max_length=12, verbose_name='شناسه کالا'),
        ),
    ]
