# Generated by Django 4.2.9 on 2025-05-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_identify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='identify',
            field=models.CharField(help_text='این فیلد به صورت خودکار جنریت میشود.', max_length=12, null=True, verbose_name='شناسه کالا'),
        ),
    ]
