# Generated by Django 4.2.9 on 2025-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_product_identify'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='more_description',
            field=models.TextField(blank=True, help_text='اگر در فیلد قبلی، توضیحات شما زیاد است لطفا در این قسمت ادامه ی ان را بنویسید', null=True, verbose_name='توضیحات بیشتر'),
        ),
    ]
